### ISSUE TITLE
Cirq measurement operators in different bases

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/qbraid-qir#138]
In Cirq, measurement gates typically default to the computational (Z) basis. However, it's possible to measure in different bases as well. Should verify measurement basis before applying `pyqir._native.mz` and use other measurement basis if possible/needed. Not sure what all is supported by pyqir in this regard. If this is not possible in pyqir, we should raises an exception when we encounter Cirq measurement operators that are not in the Z basis.

https://github.com/qBraid/qbraid-qir/blob/5d9ce6bc67732aa59fa89f0a1a16b039a78091f3/qbraid_qir/cirq/opsets.py#L54
https://github.com/qBraid/qbraid-qir/blob/5d9ce6bc67732aa59fa89f0a1a16b039a78091f3/qbraid_qir/cirq/opsets.py#L78-L79

Reference:
- https://quantumai.google/reference/python/cirq/measure_paulistring_terms
- https://quantumai.google/cirq/build/pauli_observables

**Comment by TheGupta2012** [comment]
I feel that we can just transform the basis to Z if `PauliX` or `PauliY` are used as measurement ops. This can be done by - 
1. Applying an $\mathcal{H}$ gate on the qubit having `PauliX` as the meas. basis
2. Applying $S^{\dagger}$ followed by $H$ gate on the qubit having `PauliY` as the meas. basis
