### ISSUE TITLE
Add support for `switch` statements in qasm3_to_qir converter

### ISSUE THREAD

**Issue by TheGupta2012** [qBraid/qbraid-qir#80]
### Feature Description

- openqasm 3 also supports [switch statements](https://openqasm.com/language/classical.html#the-switch-statement) which allow users to condition statement execution based on integral variables. 

### Implementation (Optional)

- The `pyqir._native` module does have a definition of the `Switch` construct but it is not entirely clear how that can be incorporated into the converter. A good starting point would be the [`pyqir._native` definition](https://github.com/qir-alliance/pyqir/blob/main/pyqir/pyqir/_native.pyi#L781) and the [openqasm switch reference](https://openqasm.com/language/classical.html#the-switch-statement)

- It would be good to have a handler for the switch, like the [`_visit_branching_statement`](https://github.com/qBraid/qbraid-qir/blob/975744c4c740f36693e0bf9199015b7b82e82fad/qbraid_qir/qasm3/visitor.py#L1112). Since `switch` is also a type of branching instruction, we can either expand this method or create a new handler.

**Comment by anushkrishnav** [comment]
I will take a look at this and work on it

**Comment by TheGupta2012** [comment]
Hi @anushkrishnav, I got an email about your comment on this issue. 
You can surely go for it if you're still interested!
